language: python

dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5"

install:
  - python -m pip install git+https://github.com/mideind/Tokenizer#egg=tokenizer
  - python -m pip install git+https://github.com/mideind/ReynirPackage#egg=reynir
  - python -m pip install git+https://github.com/mideind/Icegrams#egg=icegrams
  - python setup.py develop

script:
  - python -m pytest

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
